on:
  pull_request:

jobs:
  update_leanapap:
    runs-on: ubuntu-latest
    name: Update LeanAPAP
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install elan
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
          ~/.elan/bin/lean --version
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: Install python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install Lean dependencies
        run: |
          pip install mathlibtools

      - name: Build project
        run: |
          leanproject get-mathlib-cache
          lean --make src
